name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  # === Linux (Ubuntu 24.04) ===
  linux64:
    runs-on: ubuntu-24.04
    steps:
      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install build-essential pkg-config libasound2-dev libflac-dev libsdl2-dev zip zlib1g-dev cmake ninja-build
      - uses: actions/checkout@v4
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Configure
        run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_DEV_BUILD=ON -DENABLE_DEBUGGER=ON
      - name: Build
        run: cmake --build build
      - name: Package artifact
        run: mkdir dist && cp build/mednafen ./COPYING dist/
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mednafen (Linux)
          path: dist/*

  # === Windows (64-bit) ===
  windows64:
    runs-on: windows-latest
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          architecture: x64
          static: 1
          version: 12.2.0 
      - name: Add MinGW to PATH
        run: echo "C:\\mingw64\\bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Build Ogg manually
        run: |
          git clone https://github.com/xiph/ogg.git
          cd ogg
          mkdir build && cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
          mingw32-make
          mingw32-make install
      - name: Build FLAC manually
        run: |
          git clone https://github.com/xiph/flac.git
          cd flac
          mkdir build && cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DINSTALL_MANPAGES=OFF -DOGG_INCLUDE_DIR=C:/mingw64/include -DOGG_LIBRARY=C:/mingw64/lib/libogg.a ..
          mingw32-make
          mingw32-make install
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install sdl2 zlib glew freeglut libiconv --triplet x64-mingw-static
      - name: Configure
        run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-static" -DCMAKE_EXE_LINKER_FLAGS="-static" -DCMAKE_TOOLCHAIN_FILE=%CD%\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake
      - name: Build
        run: cmake --build build
      - name: Package artifact
        run: mkdir dist && copy build\\mednafen.exe COPYING dist\\
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mednafen (Windows)
          path: dist\\*