name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  # === Linux (Ubuntu 20.04) ===
  linux64:
    runs-on: ubuntu-24.04
    steps:
      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install build-essential pkg-config libasound2-dev libflac-dev libsdl2-dev zip zlib1g-dev cmake ninja-build
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_DEV_BUILD=ON -DENABLE_DEBUGGER=ON
      - name: Build
        run: cmake --build build
      - name: Package artifact
        run: mkdir dist && cp build/src/mednafen ./COPYING dist/
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mednafen (Linux)
          path: dist/*