name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  # === Linux (Ubuntu 24.04) ===
  linux64:
    runs-on: ubuntu-24.04
    steps:
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config libasound2-dev libflac-dev \
            libsdl2-dev zip zlib1g-dev cmake ninja-build
      - uses: actions/checkout@v4
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Configure
        run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_DEV_BUILD=ON -DENABLE_DEBUGGER=ON
      - name: Build
        run: cmake --build build
      - name: Package artifact
        run: mkdir dist && cp build/mednafen ./COPYING dist/
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mednafen (Linux)
          path: dist/*

  # === Windows (64-bit) ===
  windows64:
    runs-on: ubuntu-20.04
    steps:
      - name: Add MXE repository and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget
          wget -qO - https://pkg.mxe.cc/repos/apt/gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] http://pkg.mxe.cc/repos/apt $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build \
            mxe-x86-64-w64-mingw32.static-glew \
            mxe-x86-64-w64-mingw32.static-flac \
            mxe-x86-64-w64-mingw32.static-sdl2 \
            mxe-x86-64-w64-mingw32.static-zlib \
            mxe-x86-64-w64-mingw32.static-freeglut \
            mxe-x86-64-w64-mingw32.static-libiconv
      - uses: actions/checkout@v4
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Configure
        run: cmake -S . -Bbuild -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_DEV_BUILD=ON -DENABLE_DEBUGGER=ON \
            -DCMAKE_CXX_FLAGS="-static" \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
      - name: Build
        run: cmake --build build
      - name: Package artifact
        run: mkdir dist && cp build/mednafen ./COPYING dist/
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mednafen (Windows)
          path: dist\\*